# Generated by Django 5.0.6 on 2024-07-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
